# DynathiGA4Analytics
# Voor Firebase Analytics / Google Analytics app gebruik je GA4 Measurement Protocol.

enabled: false

firebase:
  project-name: "DynathiSMP"
  analytics-label: "firebase_ga4"

server:
  id: "dynathismp"
  name: "DynathiSMP"
  host: "DynathiSMP.mcsh.io"
  platform: "mcsh"

measurement-id: "G-XXXXXXXXXX"
api-secret: "PASTE_YOUR_API_SECRET_HERE"
use-eu-endpoint: true
client-id: "dynathismp-mcsh-server"

privacy:
  hash-player-uuid: true
  send-player-name: false
  send-world-name: true

tracking:
  server-start: true
  server-stop: true
  player-join: true
  player-quit: true
  player-death: true
  player-command: false
  player-chat: false
  online-count-task: true
  online-count-minutes: 5

debug: false
